### ISSUE TITLE
Saving model for later use

### ISSUE THREAD

**Issue by jodrodriguezpo** [ratschlab/SOM-VAE#2]
Hi, 
I would like to know if it is possible to save a trained model (SOMVAE class) in hard drive and how to do it. I'm using the class code from Jupyter Notebook. Thanks for your help.

**Comment by fortuin** [comment]
Thanks for your question. If you look at the code in the `somvae_train.py`, you can see how we do the model saving. We first [set up a model saver](https://github.com/ratschlab/SOM-VAE/blob/ac7866453f87896a66c8ea35e9bdcf9c44cb92f1/som_vae/somvae_train.py#L191) before training and then use it to [save model snapshots](https://github.com/ratschlab/SOM-VAE/blob/ac7866453f87896a66c8ea35e9bdcf9c44cb92f1/som_vae/somvae_train.py#L212) during training. Those snapshots can then be [restored again](https://github.com/ratschlab/SOM-VAE/blob/ac7866453f87896a66c8ea35e9bdcf9c44cb92f1/som_vae/somvae_train.py#L258) from a similar saver object. Alternatively, you can also use other methods to [save and restore](https://www.tensorflow.org/guide/saved_model) TensorFlow models. I hope this helps!
