### ISSUE TITLE
Use temporal data with shape: [batch_size, seq_length, n_features]

### ISSUE THREAD

**Issue by psanch21** [ratschlab/SOM-VAE#3]
Hi! I have some data I would like to test on your model but I cant manage to train it. The dataset contains N sequences with length 100 and 10 features in each time step. How should I set the parameters / network architecture? Thank you in advance.

**Comment by fortuin** [comment]
You should set `mnist=False` and `input_channels=n_features` when constructing the model, If you want the model to incorporate the time series component with the Markov model, you will have to train on single sequences as batches, that is, one batch would have the shape `[seq_length, n_features]`. I hope this helps!

**Comment by psanch21** [comment]
Yeah, it worked! Thank you for your response!
