### ISSUE TITLE
What does 'input_length' and 'input_channels' and 'z_e_old' mean and what role do they play?

### ISSUE THREAD

**Issue by sungreong** [ratschlab/SOM-VAE#4]
Hi. Thank you for your good paper. 👍 
I have some questions. :)

1. I want to apply your code to tabular data, but I wonder what  'input_length' and 'input_channels'  do.

2. When I look at your code, I think the function called z_e_old is part of the time considerations. Why does it take time to think about it? And if so, can I use that to the tabular data as well? Or how do I transform that function?

**Comment by fortuin** [comment]
Hi! I agree that the nomenclature could be improved in terms of clarity. Basically it is like this:
- If you work on image data, you should set `mnist=True` and the inputs will be expected to be of shape `[batch_size, input_length, input_channels, 1]`
- If you work on non-image data, you should set `mnist=False` and the inputs will be expected to be of shape `[batch_size, input_channels]`
- If you don't work on time series, you should set `gamma` and `tau` to zero
- If you do work on time series, you should set `gamma` and `tau` to some non-zero value (e.g., to 1.0) and use single time courses as minibatches, i.e., your inputs should be of shape `[time_steps, input_channels]`

Hope this helps!
